### ISSUE TITLE
Issue with adding firebird 3.0 connection

### ISSUE THREAD

**Issue by mkmita** [BlackbirdSQL/Firebird-DDEX-SqlEditor#85]
Hello,

I can't make this tool connect to firebird 3.0 database.

I enter all connection details. after click test connection, so i get successful connection info.

![Screenshot 2024-10-17 141754](https://github.com/user-attachments/assets/ebc5982d-35a7-4c1d-9adc-7e74e1938877)

After i try to click ok and add connection i get error message.

![Screenshot 2024-10-17 141632](https://github.com/user-attachments/assets/d778bde6-18d7-4c21-86c7-530f70b5060c)

Can you point me to some direction please or is this a bug?

Best Regards.

**Comment by BlackbirdSQL** [comment]
I believe there was a bug that crept into one of the recent releases which caused this and was fixed a couple of months ago.
The update was not uploaded because there was no feedback on anyone encountering the issue, so it was skipped with the intention to include the fix in the next major release, version 14.6.0.0.
If I'm not mistaken it was part of the bug fix for #81 which was uploaded to the VSIX Gallery for user testing.
I will upload the major release as version 14.5.2.0, either today or tomorrow, and let you know as soon as that is done.
If that resolves your issue, 14.5.2.0 will be bumped to 14.6.0.0.

**Comment by BlackbirdSQL** [comment]
Release 14.5.2.0 is available for download. The change log can be viewed at discussion #86.
Let me know if this resolves the problem.

Regards.

**Comment by BlackbirdSQL** [comment]
Release 14.5.3.0 is available for download. This release supersedes release 14.5.2.0 with several enhancements.
The change log can be viewed at discussion #87.
Let me know if this resolves the problem.

Regards.

**Comment by mkmita** [comment]
> Release 14.5.3.0 is available for download. This release supersedes release 14.5.2.0 with several enhancements. The change log can be viewed at discussion #87. Let me know if this resolves the problem.
> 
> Regards.

Hello, thank you for your swift update.

I'm testing 14.5.3.0 release and problem still there.

Let me know if i can help with something.

Best Regards.

**Comment by BlackbirdSQL** [comment]
Could you send me screenshots of the connection dialog page and the first page of the `Advanced` properties' popup.
Also the full string of the database if it's not fully visible in the screenshot.

Do you have FlameRobin installed. If so, are you able to connect using it?

If you don't, I would suggest installing it. It's a lightweight program.
Then you can use the dropdowns within BlackbirdSql to select the server and database that should be picked up from FlameRobin, and we can work it from there to establish what the issue may be.

**Comment by BlackbirdSQL** [comment]
Further, all connection open calls by BlackbirdSql will throw an expected exception. Expected exceptions are only displayed in the output window in the `BlackbirdSql` section for the Debug build, not the Release build.

I will add an option in `User Options` under `BlackbirdSQL Server Tools > Ddex Provider > Debug` to enable output of  expected exceptions to the output window in the Release build. That may provide further information.

**Comment by BlackbirdSQL** [comment]
Release 14.5.3.1 is available for download. The change log can be viewed at discussion #88 .

This release includes a __User Option__ under `BlackbirdSQL Server Tools > Ddex Provider > Debug > Expected exceptions`.
There is also a fix to a possible bug where the connection dialog could be attempting to open a connection that is already open. It may be possible this was throwing an exception.

I would recommend that before you attempt any of my other suggestions you upgrade to this release then temporarily enable `Expected exceptions`. That should report an exception in the VS output window under BlackbirdSql.

Please keep me updated.

Thanks, Greg.

**Comment by BlackbirdSQL** [comment]
Release 14.5.3.1002 is available for download. The change log can be viewed at discussion #90  .

This release includes a __User Option__ under `BlackbirdSQL Server Tools > Ddex Provider > Debug > Expected exceptions`.
This patch also addresses a couple of glitches within the connection dialog.

I would recommend that before you attempt any of my other suggestions you upgrade to this release then temporarily enable `Expected exceptions`. That should report an exception in the VS output window under BlackbirdSql.

Please keep me updated.

Thanks, Greg.

**Comment by BlackbirdSQL** [comment]
Hi @mkmita ,

Has you issue been resolved?

Regards, Greg

**Comment by mkmita** [comment]
Hi, i check it bug was not resolved no. I will try to enable exceptions and let you know if i get anything in the logs. Best Regards.
